services:
  mongo:
    image: mongo:6.0.6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: lms
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
